cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import product_list, other_page, product_detail

app_name = 'main'
urlpatterns = [
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('others/<str:page>/', other_page, name='other'),
    path('', product_list, name='product_list'),
]

orders/urls.py
from django.urls import path

from .views import order_create, admin_order_detail


app_name = 'orders'
urlpatterns = [
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('create/', order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
<h1>Корзина</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                {% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>{{ item.quantity }}</td>
        <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'main:product_list' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
    </div>
</div>
{% endblock %}