cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import product_list, other_page, product_detail

app_name = 'main'
urlpatterns = [
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('others/<str:page>/', other_page, name='other'),
    path('', product_list, name='product_list'),
]

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='Алиас')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')
    super_category = models.ForeignKey('SuperCategory', on_delete=models.PROTECT, null=True,
                                       blank=True, verbose_name='Надкатегория')


class SuperCategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_category__isnull=True)


class SuperCategory(Category):
    objects = SuperCategoryManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name', )
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class SubCategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_category__isnull=False)


class SubCategory(Category):
    objects = SubCategoryManager()

    def __str__(self):
        return '%s - %s' % (self.super_category.name, self.name)

    class Meta:
        proxy = True
        ordering = ('super_category__order', 'super_category__name',
                    'order', 'name', )
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(SubCategory, related_name='products', on_delete=models.PROTECT,
                                 verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Алиас')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='Остаток')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    OPTIONS = (
        ('n', 'Не установлено'),
        ('b', 'Лидер продаж'),
        ('s', 'Скидка'),
    )
    status = models.CharField(max_length=1, choices=OPTIONS, blank=True, default='n',
                              verbose_name='Статус')
    discount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Скидка', blank=True, default=0)

    class Meta:
        ordering = ('-created', 'available', )
        index_together = (('id', 'slug'), )
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.id, self.slug])

main/forms.py
from django import forms

from .models import SuperCategory, SubCategory


class SubCategoryForm(forms.ModelForm):
    super_category = forms.ModelChoiceField(
        queryset=SuperCategory.objects.all(), empty_label=None,
        label='Надкатегория', required=True,
    )

    class Meta:
        model = SubCategory
        fields = '__all__'

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

from .models import Product, SubCategory
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = SubCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(SubCategory, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'main/index.html', {'category': category,
                                               'categories': categories,
                                               'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    extra = Product.objects.exclude(id=id).filter(category=product.category)[:4]
    cart_product_form = CartAddProductForm()
    return render(request, 'main/product_detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form,
                                                        'extra': extra})


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

main/templates/main/about.html
{% extends "layout/basic.html" %}



{% block content %}
<div class="section">
    <div class="container">
{% lorem ipsum %}
    </div>
</div>
{% endblock %}

main/templates/main/contacts.html
{% extends "layout/basic.html" %}

{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-fistashka fixed-top">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="{% url 'main:product_list' %}">
                Le Fleur
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar top-bar"></span>
                <span class="navbar-toggler-bar middle-bar"></span>
                <span class="navbar-toggler-bar bottom-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="{% static 'img/blurred-image-1.jpg' %}">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="scrollToDownload()">
                        <p>Главная</p>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink1" data-toggle="dropdown">
                        <i class="now-ui-icons files_single-copy-04"></i>
                        <p>Каталог</p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="./index.html">
                            <i class="now-ui-icons business_chart-pie-36"></i> All components
                        </a>
                        <a class="dropdown-item" target="_blank" href="https://demos.creative-tim.com/now-ui-kit/docs/1.0/getting-started/introduction.html">
                            <i class="now-ui-icons design_bullet-list-67"></i> Documentation
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown megamenu"><a id="megamneu" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">
                    <i class="now-ui-icons files_single-copy-04"></i>
                    Mega Menu
                </a>
                    <div aria-labelledby="megamneu" class="dropdown-menu border-0 p-0 m-0">
                        <div class="container">
                            <div class="row bg-white rounded-0 m-0 shadow-sm">
                                <div class="col-lg-7 col-xl-8">
                                    <div class="p-4">
                                        <div class="row">
                                            <div class="col-lg-6 mb-4">
                                                <h6 class="font-weight-bold text-uppercase">MegaMenu heading</h6>
                                                <ul class="list-unstyled">
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0">Unique Features</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Image Responsive</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Auto Carousel</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Newsletter Form</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-lg-6 mb-4">
                                                <h6 class="font-weight-bold text-uppercase">MegaMenu heading</h6>
                                                <ul class="list-unstyled">
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Unique Features</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Image Responsive</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Auto Carousel</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Newsletter Form</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-lg-6 mb-4">
                                                <h6 class="font-weight-bold text-uppercase">MegaMenu heading</h6>
                                                <ul class="list-unstyled">
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Unique Features</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Image Responsive</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Auto Carousel</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Newsletter Form</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-lg-6 mb-4">
                                                <h6 class="font-weight-bold text-uppercase">MegaMenu heading</h6>
                                                <ul class="list-unstyled">
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Unique Features</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Image Responsive</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Auto Carousel</a></li>
                                                    <li class="nav-item"><a href="" class="nav-link text-small pb-0 ">Newsletter Form</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-5 col-xl-4 px-0 d-none d-lg-block" style="background: center center url(https://res.cloudinary.com/mhmd/image/upload/v1556990826/mega_bmtcdb.png)no-repeat; background-size: cover;"></div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:other' page='contacts' %}" onclick="scrollToDownload()">
                        <p>Контакты</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:other' page='about' %}" onclick="scrollToDownload()">
                        <p>О нас</p>
                    </a>
                </li>
                <li class="nav-item">
                    <div class="cart">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                        <a class="btn btn-fistashka btn-round" href="{% url 'cart:cart_detail' %}" type="button">
                            <i class="now-ui-icons shopping_bag-16"></i> Корзина:
                            {{ total_items }} товаров{{ total_items|pluralize }},
                            {{ cart.get_total_price }} руб.
                        </a>
                        {% else %}
                        <button class="btn btn-fistashka btn-round" type="button" disabled>
                            <i class="now-ui-icons shopping_bag-16"></i> Корзина пуста
                        </button>
                        {% endif %}
                        {% endwith %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}
{% block header%}
<div class="container-map">
    <iframe src="https://maps.google.com/maps?q=fix%20my%20device&amp;t=&amp;z=17&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" style="border: 0px none; pointer-events: auto;" allowfullscreen="" width="100%" height="570" frameborder="0"></iframe>
</div>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">

        <h2 class="title">Отправьте нам сообщение</h2>
        <div class="row">
            <div class="col-md-6">
                <p class="description">Вы можете связаться с нами по любому поводу, связанному с нашей продукцией. Мы свяжемся с вами так быстро, насколько возможно.<br><br>
                </p>
                <form role="form" id="contact-form" method="post">
                    <div class="form-group bmd-form-group">
                        <label for="name" class="bmd-label-floating">Ваше имя</label>
                        <input type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group bmd-form-group">
                        <label for="exampleInputEmails" class="bmd-label-floating">Email</label>
                        <input type="email" class="form-control" id="exampleInputEmails">
                        <span class="bmd-help">Мы не передадим никому вашу конфиденциальную информацию.</span>
                    </div>
                    <div class="form-group bmd-form-group">
                        <label for="phone" class="bmd-label-floating">Телефон</label>
                        <input type="text" class="form-control" id="phone">
                    </div>
                    <div class="form-group label-floating bmd-form-group">
                        <label class="form-control-label bmd-label-floating" for="message">Ваше сообщение</label>
                        <textarea class="form-control" rows="6" id="message"></textarea>
                    </div>
                    <div class="submit text-center">
                        <input type="submit" class="btn btn-fistashka btn-raised btn-round" value="Связаться с нами">
                    </div>
                </form>
            </div>
            <div class="col-md-4 ml-auto">
                <div class="info info-horizontal">
                    <div class="description">
                        <h4 class="info-title"><i class="now-ui-icons location_pin"></i>  Найдите нас по адресу</h4>
                        <p> Bld Mihail Kogalniceanu, nr. 8,<br>
                            7652 Bucharest,<br>
                            Romania
                        </p>
                    </div>
                </div>
                <div class="info info-horizontal">
                    <div class="description">
                        <h4 class="info-title"><i class="now-ui-icons ui-1_bell-53"></i>  Позвоните нам</h4>
                        <p> Michael Jordan<br>
                            +40 762 321 762<br>
                            Mon - Fri, 8:00-22:00
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block content %}
<div class="section section-catalog">
<div class="container">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-fistashka navbar-light navbar-custom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#example-navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:product_list' %}">Все товары</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Популярные</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Новые</a>
                    </li>
                </ul>
                <form class="form-inline ml-auto">
                    <div class="form-group has-white">
                        <input type="text" class="form-control" placeholder="Поиск">
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <!--/.Navbar-->
    <div class="row">

                {% for product in products %}
                <div class="col-12 col-md-4 col-lg-3">
                    <div class="blog-card blog-card-blog">
                        <div class="blog-card-image">
                            <a href="#"> <img class="img" src="http://placehold.it/800x600/f44242/fff"> </a>
                            <div class="ripple-cont"></div>
                        </div>
                        <div class="blog-table">
                            <h6 class="card-category text-info">{{ product.category }}</h6>
                            <h4 class="text-center">
                               {{ product.name }}
                                {% if product.status == 'b' %}
                                <span class="badge badge-success">Лидер продаж</span>
                                {% elif product.status == 's' %}
                                <span class="badge badge-info">На скидке</span>
                                {% endif %}
                            </h4>
                            <p class="text-center">{{ product.price }} руб.</p>
                            <div class="ftr text-center">
                                <button class="btn btn-fistashka btn-icon btn-round" data-toggle="tooltip" data-placement="top" title="Добавить в корзину">
                                    <i class="now-ui-icons shopping_cart-simple"></i>
                                </button>
                                <a class="btn btn-fistashka btn-icon btn-round" href="{{ product.get_absolute_url }}" data-toggle="tooltip" data-placement="top" title="Подробнее">
                                    <i class="now-ui-icons text_align-left"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

    </div>
</div>

</div>
{% endblock %}

main/templates/main/product_detail.html
{% extends "layout/basic.html" %}

{% load static %}

{% block title %}
{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<div class="section">
<div class="container">
    <div class="row">
        <div class="col-main col-md-12">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Главная</a></li>
            <li class="breadcrumb-item"><a href="#">{{ product.category.super_category.name }}</a></li>
            <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
        </ol>
    </nav>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <h1>{{ product.name }}</h1>
    <h4><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h4>
    <p class="price">${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
    </form>
                </div>
            </div>
            <div class="card card-nav-tabs card-plain">
                <div class="card-header card-header-danger">
                    <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
                    <div class="nav-tabs-navigation">
                        <div class="nav-tabs-wrapper">
                            <ul class="nav nav-tabs" data-tabs="tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#home" data-toggle="tab">Описание</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#updates" data-toggle="tab">Дополнительная информация</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div><div class="card-body ">
                <div class="tab-content">
                    <div class="tab-pane active" id="home">
                        <p>{{ product.description|linebreaks }}</p>
                    </div>
                    <div class="tab-pane" id="updates">
                        <p> I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that&#x2019;s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I think that&#x2019;s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. </p>
                    </div>
                </div>
            </div>
                {% if extra %}
                <div class="col-main col-md-12">
                    <h2>Обратите внимание:</h2>
                </div>
<div class="row">
                {% for product in extra %}
                <div class="col-12 col-md-4 col-lg-3">
                    <div class="blog-card blog-card-blog">
                        <div class="blog-card-image">
                            <a href="#"> <img class="img" src="http://placehold.it/800x600/f44242/fff"> </a>
                            <div class="ripple-cont"></div>
                        </div>
                        <div class="blog-table">
                            <h6 class="card-category text-info">{{ product.category }}</h6>
                            <h4 class="text-center">
                                {{ product.name }}
                            </h4>
                            <p class="text-center">{{ product.price }} руб.</p>
                            <div class="ftr text-center">
                                <button class="btn btn-fistashka btn-icon btn-round" data-toggle="tooltip" data-placement="top" title="Добавить в корзину">
                                    <i class="now-ui-icons shopping_cart-simple"></i>
                                </button>
                                <a class="btn btn-fistashka btn-icon btn-round" href="{{ product.get_absolute_url }}" data-toggle="tooltip" data-placement="top" title="Подробнее">
                                    <i class="now-ui-icons text_align-left"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
</div>
                {% endif %}
            </div>
    </div>
</div>
</div>
</div>
{% endblock %}